title: Kassio Borges
email: kassioborgesm@gmail.com
description: Some ruby, neovim, communication or anything else...
baseurl: ""
url: "http://localhost:4000"
contact_list:
  - service: gitlab
    name: kassio
    url: "http://gitlab.com/kassio"
    icon: "icon-gitlab.svg"
  - service: github
    name: kassio
    url: "http://github.com/kassio"
    icon: "icon-github.svg"
  - service: linkedin
    name: kassioborges
    url: "https://www.linkedin.com/in/kassioborges"
    icon: "icon-linkedin.svg"
  - service: email
    name: "kassioborgesm@gmail.com"
    url: "mailto:kassioborgesm@gmail.com"
    icon: "icon-email.svg"
  - service: twitter
    name: kassioborgesm
    url: "https://twitter.com/kassioborgesm"
    icon: "icon-twitter.svg"
  - service: feed
    name: "feed"
    url: "/feed.xml"
    icon: "icon-feed.svg"

markdown: kramdown
exclude: ["bin/*", "README.md"]
